### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by xeor** [lemonldap-ng-controller/lemonldap-ng-controller#76]
**What happened**:
Long time since last activity in project

**What you expected to happen**:
More activity, or some info in the readme of it is deprecated, feature complete, slow moving or if everyone is using something else...?

**Comment by sathieu** [comment]
I'm sorry, but this project is no longer active. I've changed job and my new job doesn't use k8s (yet).

I plan to come back on this in my new job, but can't give any date.

However, I'm still here to answer questions and merge PRs.

**Comment by sathieu** [comment]
Also, I consider it almost feature complete, and I don't know other alternatives.

The most important challenge is that related software are fast moving and this can break things.

**Comment by xeor** [comment]
Thank for sharing the status :)
